- name: Deploy Spring Boot Anime Backend Applicaion
  hosts: localhost
  remote_user: hari
  tasks:
    - name: Deploy Docker image and Kubernetes resources
      k8s:
        state: present
        definition: "{{ item }}"
      with_fileglob:
        - /var/lib/jenkins/workspace/AnimeReview/Anime/kubernetes/*.yaml