---
apiVersion: v1
kind: Service
metadata:
  name: anime-service
spec:
  selector:
    app: anime
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
        - name: anime
          image: hariprasad0023/spe_backend:latest
          ports:
            - containerPort: 3307
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql-service:3307/anime_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "NewPassword"
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 9292
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 9292
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          initContainers:
#            - name: init-mysql
#              image: mysql:latest
#              command: ['sh', '-c', 'until mysqladmin ping -h mysql-service -u root -pNewPassword; do echo "Waiting for MySQL service to be available"; sleep 5; done']
#              env:
#                - name: MYSQL_ROOT_PASSWORD
#                  value: "NewPassword"
#              volumeMounts:
#                - name: mysql-persistent-storage
#                  mountPath: /var/lib/mysql