---
apiVersion: v1
kind: Service
metadata:
  name: anime-service
spec:
  selector:
    app: anime
  ports:
    - protocol: TCP
      port: 3307  # Internal port for MySQL service
      targetPort: 3307  # Target port of your MySQL database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
        - name: anime
          image: hariprasad0023/spe_backend:latest
          ports:
            - containerPort: 9292
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql-service:3306/anime_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "NewPassword"
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 9292
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 9292
#            initialDelaySeconds: 30
#            periodSeconds: 10
      initContainers:
        - name: init-mysql
          image: mysql:latest
          command: ['sh', '-c', 'until mysql -h mysql-service -u root -pNewPassword -e "CREATE DATABASE IF NOT EXISTS anime_db;"; do echo "Waiting for mysql"; sleep 5; done']
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "NewPassword"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}