apiVersion: v1
kind: Service
metadata:
  name: anime-service
spec:
  selector:
    app: anime
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
        - name: anime
          image: hariprasad0023/spe_backend:latest
          ports:
            - containerPort: 9292
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3307"
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.0.0
          args: [
            "-e",
            "-E", "filebeat.config.modules.enabled=false",
            "-E", "filebeat.modules.enabled=false"
          ]
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs/app.log
              readOnly: true
            - name: filebeat-config
              mountPath: /etc/filebeat
              readOnly: true
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
