apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animebackend
  template:
    metadata:
      labels:
        app: animebackend
    spec:
      containers:
        - name: anime-backend-container
          image: pranjalgawande/spe_backend
          ports:
            - containerPort: 9292
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE