apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          command: ["sh", "-c", "mysql -h mysql-service -u root -pNewPassword -e 'CREATE DATABASE IF NOT EXISTS anime_db;'"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "NewPassword"
            - name: MYSQL_DATABASE
              value: "anime_db"
          ports:
            - containerPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
        - name: anime
          image: hariprasad0023/spe_backend:latest
          ports:
            - containerPort: 9292
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql-service:3306/anime_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "NewPassword"
