---
- name: Deploy Spring Boot Anime Backend Applicaion
  hosts: localhost
  remote_user: pranjal
  tasks:
    - name: Deploy Docker image and Kubernetes resources
      become: false
      shell: kubectl apply -f "{{ item }}"
      with_fileglob:
        - kubernetes/*.yaml